### ISSUE TITLE
Determine why Middleman isn't minifying JS

### ISSUE THREAD

**Issue by kabeaty** [texastribune/donations-app#6]
Although the build configuration in config.rb includes 'activate :minify_javascript', which should tell Middleman to minify the JS, it doesn't seem to be minified. It would be nice performance-wise to determine why.

**Comment by rdmurphy** [comment]
I just pulled it down and ran the build, and I saw the minified files!

**Comment by kabeaty** [comment]
Closing since it is minifying but not updating the name of the file.
